name: Realmscraft
main: com.jpmiii.Realmscraft.Realmscraft
version: 0.1.1a
depend: [Vault,Votifier]
softdepend: [InventorySQL]
commands:
   rc:
      description: set compass to portal location
      usage: /rc c
      permission-message: You don't have that Realmscraft permission
