name: Realmscraft
main: com.jpmiii.Realmscraft.Realmscraft
version: 0.1
depend: [Vault,InventorySQL,CombatTag]
commands:
   jc:
      description: This is a demo command.
      usage: /jc [h] [tperm][drop] [t] [s]
      permission: Realmscraft.basic
      permission-message: You don't have Realmscraft permission
