name: Realmscraft
main: com.jpmiii.Realmscraft.Realmscraft
version: 0.1
depend: [Vault,InventorySQL]
commands:
   rc:
      description: This is a demo command.
      usage: /rc  [s]
      permission: realmscraft.s
      permission-message: You don't have Realmscraft permission
